development:
  access_key_id: 'AKIAI4P6D5W2IYBVDLSQ'
  secret_access_key: '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'

production:
  access_key_id: 'AKIAI4P6D5W2IYBVDLSQ'
  secret_access_key: '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'
